version: "3.7"

services:
  postgres:
    hostname: "postgres.ipbox.app"
    image: "postgres:12.1-alpine"
    deploy:
      restart_policy:
        condition: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: "30s"
      timeout: "30s"
    env_file:
      - ".env.production"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    hostname: "redis.ipbox.app"
    image: "redis:alpine"
    deploy:
      restart_policy:
        condition: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 6379 || exit 1"]
      interval: "30s"
    volumes:
      - "redis_data:/data"

  app: &app_base
    image: "ipbox/app:latest"
    hostname: "app.ipbox.app"
    deploy:
      replicas: 2
      restart_policy:
        condition: "on-failure"
    env_file:
      - ".env.production"
    depends_on:
      - "postgres"
      - "redis"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: "30s"
    volumes:
      - "app_data:/app/storage"

  sidekiq:
    <<: *app_base
    deploy:
      restart_policy:
        condition: "on-failure"
    command: "bundle exec sidekiq"
    hostname: "sidekiq.ipbox.app"
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: "30s"

  caddy:
    hostname: "caddy.ipbox.app"
    image: "abiosoft/caddy:latest"
    depends_on:
      - "app"
    ports:
      - "80:80"
      - "443:443"
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - "caddy_data:/root/.caddy"
    command:
      - |
        echo "
        ipbox.app
        proxy / app:3000 {
          websocket
          transparent
        }
        " > /etc/Caddyfile
        caddy --conf /etc/Caddyfile --log stdout
    deploy:
      restart_policy:
        condition: "on-failure"
      placement:
        constraints: [node.role == manager]

volumes:
  app_data:
  postgres_data:
  redis_data:
  caddy_data:
