name: Build and deploy production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: qoobaa
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: qoobaa/ipbox/app
          registry: docker.pkg.github.com
          build_extra_args: --build-arg=RAILS_ENV=production

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://51.83.254.158:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: .docker/machines/ipbox-production
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker Login
        run: docker login -u qoobaa -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

      - name: Docker Pull
        run: docker-compose -f docker-compose.production.yml pull

      - name: Deploy to Swarm
        run: docker stack deploy --with-registry-auth --prune --resolve-image changed --compose-file docker-compose.production.yml ipbox_production

      - name: Prune
        run: docker system prune -a -f
