name: Build and deploy staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: qoobaa
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: qoobaa/ipbox/app
          registry: docker.pkg.github.com
          build_extra_args: --build-arg=RAILS_ENV=production

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_REMOTE_HOST: tcp://51.83.248.131:2376
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker Login
        run: docker --tlsverify -H $DOCKER_REMOTE_HOST --tlscacert=.docker/machines/ipbox-staging/ca.pem --tlscert=.docker/machines/ipbox-staging/cert.pem --tlskey=.docker/machines/ipbox-staging/key.pem login -u qoobaa -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

      - name: Deploy to Swarm
        run: docker --tlsverify -H $DOCKER_REMOTE_HOST --tlscacert=.docker/machines/ipbox-staging/ca.pem --tlscert=.docker/machines/ipbox-staging/cert.pem --tlskey=.docker/machines/ipbox-staging/key.pem stack deploy --compose-file docker-compose.staging.yml ipbox_staging --with-registry-auth --prune

      - name: Prune
        run: docker --tlsverify -H $DOCKER_REMOTE_HOST --tlscacert=.docker/machines/ipbox-staging/ca.pem --tlscert=.docker/machines/ipbox-staging/cert.pem --tlskey=.docker/machines/ipbox-staging/key.pem system prune -a -f
