name: Build and deploy staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: qoobaa
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: qoobaa/ipbox/app
          registry: docker.pkg.github.com
          build_extra_args: --build-arg=RAILS_ENV=production

      - name: Docker Tag
        run: docker tag docker.pkg.github.com/qoobaa/ipbox/app:latest ipbox/app:latest

      - name: Push Docker image
        run: docker push ipbox/app:latest

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_REMOTE_HOST: tcp://51.83.248.131:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: .docker/machines/ipbox-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Swarm
        run: docker stack deploy --with-registry-auth --prune --compose-file docker-compose.staging.yml ipbox_staging

      - name: Prune
        run: docker system prune -a -f
